### ISSUE TITLE
`Claim Rewards` Should Show Rewards Cross Chain

### ISSUE THREAD

**Issue by peetzweg** [Midas-Protocol/monorepo#1096]
If I'm not on the correct chain where I earned rewards, I don't see any rewards. We should show users rewards from all chains.
In the Claim Rewards dialog it should show all rewards and should offer to switch to expeceted chain if the user is on the wrong chain for claiming a certain reward.

![demo](https://user-images.githubusercontent.com/839848/206178925-674466d8-9ea9-4aba-8594-d1abe90bb00b.gif)

Mock up:

<img width="802" alt="Screenshot 2022-12-07 at 13 24 43" src="https://user-images.githubusercontent.com/839848/206178996-a4917b74-015b-47c7-b7f0-5c39bb539a72.png">

**Comment by smartdevcom** [comment]
This issue is blocked because `await this.contracts.FusePoolLensSecondary.callStatic.getRewardsDistributorsBySupplier` doesn't work as expected.

```
const [, comptrollers] = await this.contracts.FusePoolLensSecondary.callStatic.getRewardsDistributorsBySupplier(
        account,
        { from: account }
      ); 
```
returns wrong result

Now it returns ["0x31d76A64Bc8BbEffb601fac5884372DEF910F044"] as comptrollers but it's jarvis pool, It should be Stader + pStake pools
