### ISSUE TITLE
Review of hardcoded values in front-end

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#260]

**Comment by peetzweg** [comment]
@smartdevcom can you check which values are hardcoded in the frontend. This would be very helpful to know as we had the APY bug due to hardcode block time. 
Maybe a project search with a regex can do this. A bit cumbersome but we need to know if we have any more hardcoded values in the codebase we should change.

**Comment by peetzweg** [comment]
@smartdevcom can you check which values are hardcoded in the frontend. This would be very helpful to know as we had the APY bug due to hardcode block time. 
Maybe a project search with a regex can do this. A bit cumbersome but we need to know if we have any more hardcoded values in the codebase we should change.
