### ISSUE TITLE
Phase out twap bots in favor of gelato network's automation

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#508]

**Comment by rhlsthrm** [comment]
Update from Aug 26:
- PR is here: https://github.com/Midas-Protocol/contracts/pull/360
- Resolver is done, but test is failing: https://github.com/Midas-Protocol/contracts/blob/gelato-twap/contracts/test/oracles/default/UniswapTwapPriceOracleV2Resolver.t.sol#L62
- Run test with command `forge test --block-number 20238373 --fork-url https://bsc-dataseed1.binance.org/ --match-contract UniswapTwapOracleV2ResolverTest  -vvvv`

After working test these are the next steps:
- Add to deploy script to deploy the `UniswapTwapPriceOracleV2Resolver` and add the pairs for the tokens we want to TWAP (DDD, EPX, JBRL)
- Create Gelato task that uses `UniswapTwapPriceOracleV2Resolver` as the task contract _and_ the resolver. The checker function will work to run the task when it needs to.
- Fund the Gelato account with BNB.
- Take care of the ownership since it can be used to stop the oracle.
