### ISSUE TITLE
BUSD balance is off on the Jarvis Pools / BSC

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/monorepo#654]
See: https://discord.com/channels/930077813585899561/930157130454024192/1017956923062095872

**Comment by smartdevcom** [comment]
Did last deploy fix this issue? Because I saw the differences between screenshot from discord and https://app.midascapital.xyz/56/pool/1

screenshot from discord
![image](https://user-images.githubusercontent.com/45715420/189597109-118df26f-b00b-4060-af41-50c669a31a28.png)

screenshot from current app
![image](https://user-images.githubusercontent.com/45715420/189596805-d321b67b-36c2-4ab1-b424-9b461f6a9a69.png)

**Comment by carlomazzaferro** [comment]
Can you try supplying bnb using the test account in prod, and seeing if the values are correct?

**Comment by smartdevcom** [comment]
`BUSD` balance is `0` in test account `0x82eDcFe00bd0ce1f3aB968aF09d04266Bc092e0E`

**Comment by smartdevcom** [comment]
![image](https://user-images.githubusercontent.com/45715420/189604377-4fe00874-42b5-4255-8073-5103dfd731fa.png)

**Comment by peetzweg** [comment]
Looks fine on my machine as well. Guess we need to find out how to reproduce this error. 🤔

**Comment by carlomazzaferro** [comment]
Will close for now
