### ISSUE TITLE
Issues with depositing wstDOT and xcDOT

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/monorepo#935]
https://discord.com/channels/930077813585899561/973139614942527499/1036834702214053928

**Comment by NikMidas** [comment]
@peetzweg working on this currently

**Comment by peetzweg** [comment]
Having trouble debugging this issue of minting xcDOT of Darrel:
https://discord.com/channels/930077813585899561/973139614942527499/1037005381513261056

It's this pool:
https://development.midascapital.xyz/1284/pool/1
Comptroller: `0xeB2D3A9D962d89b4A9a34ce2bF6a2650c938e185`
and this Market:
`0xa9736bA05de1213145F688e4619E5A7e0dcf4C72`

At first I thought it's just a tx timing issue due to moonbeam beeing so fast. But approval is done and just `mint` seems to fail now on. It reverts with generic error message:
`"VM Exception while processing transaction: revert"`

Trying to supply with `deployer` `0x82eDcFe00bd0ce1f3aB968aF09d04266Bc092e0E`

mint in the `USDC.wh` marketed worked fine though, so maybe a misconfiguration of the xcDOT market?

**Comment by peetzweg** [comment]
MEtamask wasn't able to get the `gasLimit`, once set manually it can submit a transaction, which will not even go out of gas but reverts without a message.

210k gas limit
https://moonbeam.moonscan.io/tx/0x4f80583efa461881b2c1b33e26a7692aa808892fb1db3f8424957c20da6c6bec
2100k gas limit
https://moonbeam.moonscan.io/tx/0xc1e3b201516fdd7f86d23cb8c62691b3e7981f408fd30c5a3d5e0f88cd331dbe

**Comment by carlomazzaferro** [comment]
completed by upgrading pool implementation
